# PostgreSQL Konfigürasyonu
spring.datasource.url=jdbc:postgresql://db:5432/mydb
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Redis Konfigürasyonu
spring.redis.host=redis
spring.redis.port=6379

# Sunucu Portu
server.port=8080
